lang: en
use_world_guard: true
region_height: 255
use_sql: false
db_host: localhost
db_port: 3306
db_name: HAB
db_table: hab
db_user: root
db_password: pass
use_economy: false
housing_cost: 100
limit_houses_per_player: false
house_limit: 5
house_max_width: 50
houses_per_row: 50
platform_y: 50
platform_width: 5
flags_allow: []
flags_deny: [ pvp ]
restrict_invite:  [ enderdragon, witherskull, witherboss, ghast ]
passByKey: false
keyId: 373
alllow_stealing: false
passOnlyByKey: false