name: HouseInaBottle
main: ru.alastar.Main
author: Alastar
description: Virtual housing
version: 1.0
depend: [WorldEdit]
softdepend: [WorldGuard, Vault, SQLLibrary]
load: POSTWORLD
commands:
     hcreate:
       description: Create housing
       permission: HAB.create
       usage: /hcreate <housename>
     hlist:
       description: List all of your housings
       permission: HAB.list
       usage: /hlist
     haccept:
       description: Accept invitation
       permission: HAB.accept
       usage: /haccept
     hdecline:
       description: Refuse invitation
       permission: HAB.decline
       usage: /hdecline
     hinvite:
       description: Inviting selected person
       permission: HAB.invite
       usage: /hinvite <housename>
     hexport:
       description: Exporting housings database to selected
       permission: HAB.export
       usage: /hexport <db>
     htele:
       description: Teleports to the specified house
       permission: HAB.tele
       usage: /htele <housename>
     hsetspawn:
       description: Sets house spawn point
       permission: HAB.setspawn
       usage: /setspawn <housename>